# Generated by Django 4.2.7 on 2023-11-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FORÇA", "Força"),
                            ("DESTREZA", "Destreza"),
                            ("CONSTITUIÇÃO", "Constituição"),
                            ("CARISMA", "Carisma"),
                            ("INTELIGÊNCIA", "Inteligência"),
                            ("SABEDORIA", "Sabedoria"),
                        ],
                        default="Força",
                        max_length=128,
                    ),
                ),
                ("intStatus", models.IntegerField()),
            ],
        ),
    ]
