# Generated by Django 4.2.7 on 2023-11-28 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("crud_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="personagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "classes",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crud_app.classe",
                    ),
                ),
            ],
        ),
    ]
